"""migration_helpers.py — reusable patterns for Supabase migrations + Python ops.

Codifies the 7 patterns proven in Phase D1 / D3 / column-grant lockout:

  1. apply_migration_sql        — read .sql file, execute in transaction
  2. generate_rollback_sql      — emit defensive DELETE/RESTORE SQL
  3. unnest_upsert              — bulk INSERT via UNNEST(...) → SELECT, ON CONFLICT
  4. column_grant_lockout       — REVOKE table-level + GRANT column-level per role
  5. subprocess_with_shape_safety — run an external script with row-count guardrails
  6. register_supabase_migration — emit the CLI repair command (agent shell can't run TTY)
  7. set_local_role_and_test    — execute SQL under SET LOCAL ROLE; rollback always

All functions are stateless and safe to import from any script. Connection
objects are passed in; this module does not own its own DB connection.

Usage in a script:

    from migration_helpers import (
        apply_migration_sql, unnest_upsert, column_grant_lockout,
        subprocess_with_shape_safety, set_local_role_and_test,
    )
"""
from __future__ import annotations

import hashlib
import json
import os
import socket
import subprocess
import sys
from pathlib import Path
from typing import Any, Callable, Sequence

import pandas as pd

try:
    import psycopg2
    from psycopg2 import errors as pg_errors
    from psycopg2.extensions import connection as PgConnection
except ImportError:
    psycopg2 = None
    pg_errors = None
    PgConnection = Any  # type: ignore

DBCONFIG_DEFAULT = Path(r"D:\verdmat-is\.dbconfig")


# ----------------------------------------------------------------------
# Connection helper (small, optional — passes through to psycopg2.connect)
# ----------------------------------------------------------------------
def open_connection(dbconfig_path: Path = DBCONFIG_DEFAULT,
                    autocommit: bool = False):
    """Open a psycopg2 connection from .dbconfig (UTF-8 BOM aware)."""
    if psycopg2 is None:
        raise RuntimeError("psycopg2 not installed")
    url = dbconfig_path.read_text(encoding="utf-8-sig").strip()
    conn = psycopg2.connect(url)
    conn.autocommit = autocommit
    return conn


# ----------------------------------------------------------------------
# 1) apply_migration_sql
# ----------------------------------------------------------------------
def apply_migration_sql(conn, path: Path) -> tuple[bool, int, str]:
    """Read a .sql file and execute it in a transaction.

    Returns (ok, rowcount, message). Caller decides whether to commit
    additional work afterward. On error, the transaction is rolled back
    and (False, 0, error_msg) is returned.

    The migration SQL is expected to contain its own BEGIN/COMMIT blocks
    or be safe to run as a single statement set. psycopg2's behavior:
    if the SQL contains explicit BEGIN/COMMIT, those are respected;
    otherwise the implicit transaction wraps the whole file.
    """
    sql = path.read_text(encoding="utf-8")
    with conn.cursor() as cur:
        try:
            cur.execute(sql)
            rowcount = cur.rowcount if cur.rowcount >= 0 else 0
        except Exception as e:
            conn.rollback()
            return False, 0, f"{type(e).__name__}: {e}"
    return True, rowcount, f"applied {path.name} ({len(sql):,} bytes)"


# ----------------------------------------------------------------------
# 2) generate_rollback_sql
# ----------------------------------------------------------------------
def generate_rollback_sql(
    out_path: Path,
    fastnums: Sequence[int],
    tables: Sequence[str],
    comment: str = "",
) -> Path:
    """Emit a defensive multi-table DELETE rollback for a fastnum batch.

    Mirrors the pattern from phase_d3_dryrun.generate_rollback. Wraps
    DELETEs in a single transaction, in REVERSE table order from the
    apply (predictions → sales_history → properties for D3, etc.).
    """
    in_list = ",".join(str(int(fn)) for fn in sorted(set(fastnums)))
    lines = [
        f"-- Rollback SQL — generated by migration_helpers.generate_rollback_sql",
        f"-- Targets {len(fastnums):,} fastnums across {len(tables)} table(s):",
        f"--   {', '.join(tables)}",
    ]
    if comment:
        lines.append(f"-- {comment}")
    lines += [
        "--",
        "-- Wrapped in a single transaction; defensive IN-list so future",
        "-- inserts on the same fastnums are not affected.",
        "",
        "BEGIN;",
    ]
    for t in tables:
        lines.append(f"DELETE FROM public.{t} WHERE fastnum IN ({in_list});")
    lines.append("COMMIT;")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path


# ----------------------------------------------------------------------
# 3) unnest_upsert
# ----------------------------------------------------------------------
def _na_to_none(series):
    return [None if pd.isna(v) else v for v in series.tolist()]


def unnest_upsert(
    conn,
    table: str,
    df: pd.DataFrame,
    column_types: dict[str, str],
    *,
    on_conflict: str = "DO NOTHING",
    conflict_cols: Sequence[str] = ("fastnum",),
    casts: dict[str, str] | None = None,
    batch_size: int = 500,
) -> int:
    """Bulk INSERT via UNNEST(...) → SELECT, with ON CONFLICT handling.

    Generalizes the phase_d1_apply / phase_d3_apply pattern. Each column
    becomes one psycopg2 named parameter passed as a typed array.

    Parameters
    ----------
    conn: live psycopg2 connection (transaction managed by caller).
    table: fully-qualified or schema-less table name (`public.x` or `x`).
    df: DataFrame whose columns are subset of column_types keys.
    column_types: ordered dict {col_name: postgres_type}.
                  Keys ARE the INSERT column list, in order.
    on_conflict: 'DO NOTHING' or 'DO UPDATE SET ...'.
    conflict_cols: which columns the ON CONFLICT clause keys on.
    casts: optional {col_name: target_type} for in-SELECT casts
           (e.g. {'matseiningar': 'jsonb'} → SELECT matseiningar::jsonb FROM unnest).
    batch_size: rows per UNNEST call (matches phase_d1/d3 default).

    Returns total rows actually INSERTed (sum of rowcounts).
    """
    if psycopg2 is None:
        raise RuntimeError("psycopg2 not installed")
    cols = list(column_types.keys())
    types = list(column_types.values())
    casts = casts or {}

    select_exprs = []
    for c in cols:
        if c in casts:
            select_exprs.append(f"{c}::{casts[c]}")
        else:
            select_exprs.append(c)
    select_clause = ",\n  ".join(select_exprs)
    insert_cols_clause = ", ".join(cols)
    unnest_args = ",\n    ".join(f"%({c})s::{types[i]}[]" for i, c in enumerate(cols))
    unnest_alias = "(" + ", ".join(cols) + ")"
    conflict_clause = (
        f"ON CONFLICT ({', '.join(conflict_cols)}) {on_conflict}"
        if conflict_cols else ""
    )

    sql = f"""
INSERT INTO {table} ({insert_cols_clause})
SELECT
  {select_clause}
FROM unnest(
    {unnest_args}
) AS src{unnest_alias}
{conflict_clause};
"""

    total = 0
    n_batches = (len(df) + batch_size - 1) // batch_size
    for i in range(n_batches):
        sub = df.iloc[i * batch_size:(i + 1) * batch_size]
        params = {c: _na_to_none(sub[c]) for c in cols}
        with conn.cursor() as cur:
            cur.execute(sql, params)
            total += cur.rowcount
    return total


# ----------------------------------------------------------------------
# 4) column_grant_lockout
# ----------------------------------------------------------------------
def column_grant_lockout(
    conn,
    table: str,
    allowlist_anon: Sequence[str],
    allowlist_auth: Sequence[str] | None = None,
) -> str:
    """REVOKE table-level SELECT and GRANT column-level allowlist per role.

    Mirrors the pattern from apply_column_grant_lockout.py.

    If allowlist_auth is None, authenticated gets the same allowlist as anon.
    Caller wraps in BEGIN/COMMIT (this function executes inside an open txn).

    Returns a short human-readable summary string.
    """
    if allowlist_auth is None:
        allowlist_auth = allowlist_anon
    cols_anon = ",\n  ".join(allowlist_anon)
    cols_auth = ",\n  ".join(allowlist_auth)
    sql = f"""
REVOKE SELECT ON public.{table} FROM anon;
REVOKE SELECT ON public.{table} FROM authenticated;
GRANT SELECT (
  {cols_anon}
) ON public.{table} TO anon;
GRANT SELECT (
  {cols_auth}
) ON public.{table} TO authenticated;
"""
    with conn.cursor() as cur:
        cur.execute(sql)
    return (
        f"public.{table}: anon={len(allowlist_anon)} cols, "
        f"authenticated={len(allowlist_auth)} cols"
    )


# ----------------------------------------------------------------------
# 5) subprocess_with_shape_safety
# ----------------------------------------------------------------------
def subprocess_with_shape_safety(
    cmd: Sequence[str],
    *,
    output_path: Path | None = None,
    rowcount_before: int | None = None,
    rowcount_after_fn: Callable[[Path], int] | None = None,
    max_shrink_pct: float = 5.0,
    timeout: int | None = None,
    cwd: Path | None = None,
) -> tuple[int, int | None, str]:
    """Run an external script with row-count drift guardrail.

    Mirrors patterns from rebuild_training_data.py + refresh_dashboard_tables.py:

      - subprocess.run with stdout/stderr captured
      - if output_path + rowcount_after_fn given, measure rowcount delta
      - if shrinkage > max_shrink_pct vs rowcount_before, return non-zero
        exit code and a clear message (caller decides rollback)

    Returns (exit_code, rowcount_after, message).
    rowcount_after is None if not measured.
    """
    # encoding="utf-8" + errors="replace" (NOT text=True): the D:\ build scripts
    # emit Icelandic + box-drawing chars (│ ─ á í ð þ ö); text=True decodes with
    # the Windows locale (cp1252), which throws UnicodeDecodeError on byte 0x81
    # in a subprocess reader thread and leaves result.stdout = None.
    # PYTHONIOENCODING=utf-8 forces the CHILD Python's stdout/stderr to utf-8
    # when piped — without it, a child that doesn't reconfigure its own stdout
    # writes cp1252 and crashes printing → / Icelandic / box-drawing chars
    # (bug #5, refresh_dashboard_tables.py). Affects child stdio only, not the
    # child's file IO (those carry their own encoding= params).
    result = subprocess.run(
        list(cmd),
        capture_output=True,
        encoding="utf-8",
        errors="replace",
        timeout=timeout,
        cwd=str(cwd) if cwd else None,
        env={**os.environ, "PYTHONIOENCODING": "utf-8"},
    )
    # None-guard: capture_output can still yield None on some interpreters/paths.
    out = result.stdout or ""
    err = result.stderr or ""
    if result.returncode != 0:
        # Many of our D:\ scripts print their error (preflight bails, halts)
        # to STDOUT, not stderr — capturing stderr alone hides the real cause.
        # Include a stdout tail (last 40 lines) so the failure is diagnosable.
        stderr_tail = err.strip()[:500]
        stdout_lines = out.strip().splitlines()
        stdout_tail = "\n".join(stdout_lines[-40:]) if stdout_lines else ""
        msg = f"subprocess failed (exit {result.returncode})"
        if stderr_tail:
            msg += f"; stderr: {stderr_tail}"
        if stdout_tail:
            msg += f"; stdout-tail:\n{stdout_tail}"
        return result.returncode, None, msg
    if output_path is None or rowcount_after_fn is None:
        return 0, None, f"subprocess ok ({len(out.splitlines())} stdout lines)"

    rowcount_after = rowcount_after_fn(output_path)
    if rowcount_before is not None and rowcount_before > 0:
        shrink_pct = 100.0 * (rowcount_before - rowcount_after) / rowcount_before
        if shrink_pct > max_shrink_pct:
            return 99, rowcount_after, (
                f"SHAPE-SAFETY VIOLATION: rowcount shrank "
                f"{shrink_pct:.2f}% > {max_shrink_pct}% "
                f"({rowcount_before:,} → {rowcount_after:,})"
            )
    return 0, rowcount_after, (
        f"subprocess ok; rowcount={rowcount_after:,} "
        f"(was {rowcount_before:,})" if rowcount_before is not None
        else f"subprocess ok; rowcount={rowcount_after:,}"
    )


# ----------------------------------------------------------------------
# 6) register_supabase_migration
# ----------------------------------------------------------------------
def register_supabase_migration(
    versions: Sequence[str],
    cli_path: str = r"D:\verdmat-is\tools\supabase\supabase.exe",
) -> str:
    """Emit the CLI repair command for the operator to run interactively.

    The agent shell cannot run interactive TTY commands. The 2026-05-21
    + 2026-05-27 Group B entries documented this pattern. This function
    is intentionally a string-emitter, not an executor — it prints the
    exact command Danni runs in a real PowerShell terminal.

    Returns a single command string.
    """
    versions_str = " ".join(versions)
    return f'{cli_path} migration repair --status applied {versions_str}'


# ----------------------------------------------------------------------
# 7) set_local_role_and_test
# ----------------------------------------------------------------------
def set_local_role_and_test(
    conn,
    role: str,
    sql: str,
    *,
    expect_error_class: type | None = None,
):
    """Execute SQL inside SET LOCAL ROLE; always ROLLBACK.

    Used for sanity probes (anon view-count match, anon 42501 on excluded
    columns). Mirrors the pattern from apply_column_grant_lockout.py.

    Returns:
      - On success: ('ok', result_rows_or_None, no_error)
      - On expected error class: ('expected_error', None, error_message)
      - On unexpected error: ('unexpected_error', None, error_message)
    """
    if psycopg2 is None:
        raise RuntimeError("psycopg2 not installed")
    with conn.cursor() as cur:
        try:
            cur.execute(f"SET LOCAL ROLE {role}")
            cur.execute(sql)
            try:
                rows = cur.fetchall()
            except Exception:
                rows = None
        except Exception as e:
            conn.rollback()
            cls = type(e).__name__
            if expect_error_class is not None and isinstance(e, expect_error_class):
                return "expected_error", None, f"{cls}: {str(e).strip()[:200]}"
            return "unexpected_error", None, f"{cls}: {str(e).strip()[:200]}"
        finally:
            conn.rollback()  # always unwind SET LOCAL
        return "ok", rows, ""


# ----------------------------------------------------------------------
# Misc — small utilities used across Group C orchestration
# ----------------------------------------------------------------------
def file_md5_hex(path: Path) -> str:
    """SHA-256-but-named-md5 hex digest for input-snapshot fingerprints.

    Yes, the name says md5 for historical reasons (matches the column
    name `cpi_csv_md5` etc. in inputs_snapshots); the actual algorithm
    is SHA-256 because collision resistance matters more than speed for
    audit fingerprints. Both digests serialise to the same column.
    """
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def git_sha_head(repo_dir: Path = Path(r"D:\verdmat-is\app")) -> str | None:
    """Return HEAD SHA of the verdmat-is repo, or None if unavailable."""
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            cwd=str(repo_dir),
            stderr=subprocess.DEVNULL,
            encoding="utf-8",
            errors="replace",
            timeout=5,
            env={**os.environ, "PYTHONIOENCODING": "utf-8"},
        ).strip()
        return out or None
    except Exception:
        return None


# ----------------------------------------------------------------------
# pipeline_runs / pipeline_steps writers (shared by ALL orchestrators)
# ----------------------------------------------------------------------
# One source of truth for Group C audit logging. run_monthly.py, the daily
# sales-refresh loader, and the monthly CPI re-anchor engine all call these,
# so every orchestrator logs identically.
#
# CONVENTIONS (all three orchestrators MUST follow):
#   - exit_status is free-form text but kept to a small vocabulary so a future
#     /heilsa health check can treat it as essentially binary:
#       'success'  — run finished its intended work (INCLUDING a clean no-op).
#       'failed'   — an error aborted the run (writes rolled back).
#       'halted'   — a deliberate gate stopped the run before consequential work.
#       'crashed'  — an unexpected exception (caught by the orchestrator).
#   - NO-OP runs are RECORDED, never dropped: a no-op (kaupskra unchanged →
#     NEW=0; CPI anchor unchanged) finishes with exit_status='success' AND
#     summary={'noop': True, 'reason': '...'} so success/failed stays a clean
#     binary while the no-op remains visible/queryable in the summary.
#   - Each writer commits on its own so the audit trail survives even if a
#     later step in the same run crashes.
# ----------------------------------------------------------------------
def start_run(conn, run_type: str) -> int:
    """INSERT a pipeline_runs row at run start; return its id. Commits.

    First statement is SET TRANSACTION READ WRITE: on the transaction pooler a
    read-only session opened elsewhere (open_ro_conn's set_session readonly=True)
    can leak READ ONLY into a shared backend, so every write txn must re-assert it.
    """
    with conn.cursor() as cur:
        cur.execute("SET TRANSACTION READ WRITE")
        cur.execute(
            """
            INSERT INTO public.pipeline_runs
              (run_type, started_at, host, git_sha)
            VALUES (%s, now(), %s, %s)
            RETURNING id
            """,
            (run_type, socket.gethostname(), git_sha_head() or "unknown"),
        )
        run_id = cur.fetchone()[0]
    conn.commit()
    return run_id


def start_step(conn, run_id: int, step_name: str, step_order: int) -> int:
    """INSERT a pipeline_steps row at step start; return its id. Commits."""
    with conn.cursor() as cur:
        cur.execute("SET TRANSACTION READ WRITE")  # pooler read-only-leak guard
        cur.execute(
            """
            INSERT INTO public.pipeline_steps
              (run_id, step_name, step_order, started_at)
            VALUES (%s, %s, %s, now())
            RETURNING id
            """,
            (run_id, step_name, step_order),
        )
        step_id = cur.fetchone()[0]
    conn.commit()
    return step_id


def finish_step(
    conn,
    step_id: int,
    exit_code: int,
    *,
    rowcount_before: int | None = None,
    rowcount_after: int | None = None,
    notes: str | None = None,
    output_paths: list[str] | None = None,
    log_path: str | None = None,
) -> None:
    """UPDATE a pipeline_steps row at step end. Commits."""
    with conn.cursor() as cur:
        cur.execute("SET TRANSACTION READ WRITE")  # pooler read-only-leak guard
        cur.execute(
            """
            UPDATE public.pipeline_steps
            SET ended_at=now(),
                exit_code=%s,
                rowcount_before=%s,
                rowcount_after=%s,
                notes=%s,
                output_paths=%s,
                log_path=%s
            WHERE id=%s
            """,
            (
                exit_code, rowcount_before, rowcount_after, notes,
                json.dumps(output_paths) if output_paths else None,
                log_path, step_id,
            ),
        )
    conn.commit()


def finish_run(
    conn, run_id: int, exit_status: str, summary: dict | None = None
) -> None:
    """UPDATE a pipeline_runs row at run end. Commits.

    For a no-op run pass exit_status='success' with summary={'noop': True, ...}.
    """
    with conn.cursor() as cur:
        cur.execute("SET TRANSACTION READ WRITE")  # pooler read-only-leak guard
        cur.execute(
            """
            UPDATE public.pipeline_runs
            SET ended_at=now(), exit_status=%s, summary=%s
            WHERE id=%s
            """,
            (exit_status, json.dumps(summary) if summary else None, run_id),
        )
    conn.commit()
